# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://alexcrack.github.io/qetchosts/
title: qEtcHosts
email: a13xcrack@gmail.com
author: Alexey Avramchik
description: > # qEtcEdit is a simple util for edit hosts-file in a comfortable way
  It supports templates with list of several hosts. This template might be enabled or disabled by checkboxes.
  Util is inspired by host-switcher that hasn't supported since 2011. Thanks to author.
copyright: 'Copyright &copy; 2019 Alexey Avramchik. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
remote_theme: swcool/landing-page-theme
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/alexcrack/qetchosts